### ISSUE TITLE
Unsure of execution mechanism on windows (via cygwin)

### ISSUE THREAD

**Issue by sarnobat** [migasfree/lshw-windows-emulator#1]
I believe the pip3 installation succeeded:
```
Using pip 24.0 from /usr/lib/python3.9/site-packages/pip (python 3.9)
Requirement already satisfied: lshw in /usr/local/lib/python3.9/site-packages (0.0.1)
```

and I see 

```
/usr/local/lib/python3.9
/usr/local/lib/python3.9/site-packages
/usr/local/lib/python3.9/site-packages/lshw-0.0.1.dist-info
/usr/local/lib/python3.9/site-packages/lshw-0.0.1.dist-info/INSTALLER
/usr/local/lib/python3.9/site-packages/lshw-0.0.1.dist-info/LICENSE
/usr/local/lib/python3.9/site-packages/lshw-0.0.1.dist-info/METADATA
/usr/local/lib/python3.9/site-packages/lshw-0.0.1.dist-info/RECORD
/usr/local/lib/python3.9/site-packages/lshw-0.0.1.dist-info/REQUESTED
/usr/local/lib/python3.9/site-packages/lshw-0.0.1.dist-info/top_level.txt
/usr/local/lib/python3.9/site-packages/lshw-0.0.1.dist-info/WHEEL
```
but I don't know what to execute.

I have a feeling my installation is atypical. I don't see site-packages for any of the other 20 packages that are installed via `pip3 list`. If you have any tips let me know, else feel free to close.

**Comment by jact** [comment]
In the project requirements, it says that the target system is Windows. As it is. Cygwin is not necessary to install the software. Just have Python installed on Windows and install the package that can be found in the releases via pip.
